
# Site settings for this cinfdata instance

# Database setings
db_hostname: localhost
db_port: 3306
db_name: cinfdata
db_read_all_user: cinf_reader

# Database settings during development
dev_db_hostname: localhost
dev_db_port: 9999
dev_db_name: cinfdata

# Deployment data
deployment_root: /home/kenni/www/cinfdata
